version: '3'
services:
    web:
        image: nginx
        volumes:
            - "./.docker/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.conf"
            - ".:/home/docker"
        ports:
            - "${NGINX_PORT}:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: always
        links:
            - "symfony:symfony"


    symfony:
        build:
            context: ./.docker/php-fpm/
            args:
                - "DOCKER_USER=${DOCKER_USER}"
                
        image: symfony3_docker
        restart: always
        links:
            - "mysqldb:db"
        volumes:
            - ".:/home/docker"
            - "./.docker/etc/php/php.ini:/usr/local/etc/php/conf.d/custom.ini"
        working_dir: "/home/docker"
        user: "${DOCKER_USER}"


    mysqldb:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}


        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - "./.docker/data/db:/var/lib/mysql"


    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "${PMA_PORT}:80"
        environment:
            - "PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        links:
            - "mysqldb:db"


    mailhog:
        image: mailhog/mailhog
        ports:
            - "${MAILHOG_PORT}:8025"
            - "1025:1025"
        links:
            - "symfony:symfony"

